### ISSUE TITLE
Modificaciones de tablas org_parte_tipo y org_parte para adecuar a Mapeo de Herencia de Doctrine2

### ISSUE THREAD

**Issue by pislas** [Enterprise-Solutions/proySC#9]
En la tabla org_parte_tipo:
Poner como primary key el campo codigo.
Eliminar el campo serial org_parte_tipo_id.

En la tabla org_parte:
Eliminar el fk org_parte_tipo_id.
Agregar una columna org_parte_tipo_codigo, que sea el fk a la
tabla org_parte_tipo.

**Comment by mimt** [comment]
Solucionado
